apiVersion: 1

datasources:
  - name: DS_ELASTICSEARCH
    type: elasticsearch
    access: proxy
    url: http://localhost:9200
    password: ''
    user: ''
    database: apm-*
    basicAuth: false
    isDefault: true
    jsonData:
      esVersion: 7.10.0
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
    readOnly: false
